### ISSUE TITLE
If statement in Throttler doesn't do anything

### ISSUE THREAD

**Issue by lfmunoz** [afedulov/fraud-detection-demo#3]
You have Preconditions.checkArgument(  maxRecordsPerSecond == -1 ... )

Then in the next line you do if(maxRecordsPerSecond == -1) which will never be the case. 

https://github.com/afedulov/fraud-detection-demo/blob/a50d989c8077c407b6ecc82ff91d865f8cde9dfb/webapp/src/main/java/com/ververica/demo/backend/datasource/Throttler.java#L44

I was loooking at  this because I had question about backpressure with a source and it looks like it is not possible to backpressure a datasource you just gotta Throttle . I thought doing thread sleep might have other consequences in blocking the entire task. 

https://stackoverflow.com/questions/61465789/how-do-i-create-a-flink-richparallelsourcefunction-with-backpressure

**Comment by afedulov** [comment]
Thanks for the comment. I have adopted this Throttler from an internal code base and it seems that the author changed his mind along the way and did not quite make that change consistent. 

As for your question with the OOM exceptions - try adding a dummy data shuffle stage between your source and the buffering function (add a keyBy).

If this does not help, try to disable operator chaining with
`StreamExecutionEnvironment.disableOperatorChaining()` as described [here](https://ci.apache.org/projects/flink/flink-docs-stable/dev/stream/operators/#task-chaining-and-resource-groups).

Flink's backpressure mechanism is based on the credit-based flow control over network buffers - see the detailed explanation [here](https://flink.apache.org/2019/06/05/flink-network-stack.html). If your source and the flatMap get inlined into the same thread and just handover data one to another without the network in between, there is nothing that can backpressure the data generator.

**Comment by lfmunoz** [comment]
@afedulov thank you for suggestion will try and let you know. Might be a few days as I am trying to finish some other code.

**Comment by lfmunoz** [comment]
@afedulov Removed chaining this is my pipeline

![Screenshot from 2020-05-07 13-31-23](https://user-images.githubusercontent.com/1304440/81332925-69d8c080-9069-11ea-82bd-f894e2748257.png)

It works for parallelism 1. With parallelism 3 as an example It crashes. See below.

Back pressure in Flink seems broken. It can only back pressure across network calls but what if it the stream doesn't go through a network then it just accumulates and crashes?

I tried to email you about something but the email on your website is incorrect (http://fedulov.website/), in particular about a this project I have that might interest you: https://github.com/lfmunoz/flink-dynamic-pipelines

```
java.lang.OutOfMemoryError: Java heap space
2020-05-07 18:27:37,942 ERROR org.apache.flink.runtime.util.FatalExitExceptionHandler       - FATAL: Thread 'flink-scheduler-1' produced an uncaught exception. Stopping the process...
java.lang.OutOfMemoryError: Java heap space
        at akka.dispatch.AbstractNodeQueue.<init>(AbstractNodeQueue.java:32)
        at akka.actor.LightArrayRevolverScheduler$TaskQueue.<init>(LightArrayRevolverScheduler.scala:305)
        at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:270)
        at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:236)
        at java.lang.Thread.run(Thread.java:748)
2020-05-07 18:27:35,725 ERROR org.apache.flink.runtime.util.FatalExitExceptionHandler       - FATAL: Thread 'flink-metrics-8' produced an uncaught exception. Stopping the process...
java.lang.OutOfMemoryError: Java heap space
2020-05-07 18:27:35,725 ERROR com.rabbitmq.client.impl.ForgivingExceptionHandler            - An unexpected connection driver error occured
java.lang.OutOfMemoryError: Java heap space
        at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:120)
        at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:580)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by afedulov** [comment]
Hi, I have double-checked: 

1) backpressure will manifest by the calls to ctx.collect() being blocked. This applies to sources as well as any other functions. My advice to try to disable operator chaining was not correct (same holds fo your assumption on SO that Flink does not support backpressure on sources). 

2) I do not quite know the details of how exactly the RabbitMQ sink is handling the data transfer (it is not the most popular sink in Flink, to be honest). If it does some non-blocking async transmissions, this could cause the behavior that you observe. You could do a quick test to exclude this possibility by adding another `map` operator right before the sink and let is sleep for the time similar to how long it takes for your job to normally OOM. ctx.collect() in the source should get blocked.

3) Another thing to consider is that you might indeed just not have enough memory to fill up all the buffers with the settings that you use. It could be that when you have Thread.sleep() in there, you release the memory by hitting the time limit first, so that your buffers are never reaching their maximum capacity.

4) You do not need to have `bufferedElements` as a List of Lists. The `bufferToByteArray` function will be deserialized for every subtask, so you can just directly consider data that you get partitioned - no nested lists required.

5) If you want your program to be fault tolerant, `bufferToByteArray` should become a managed Flink state.

6) Thanks for sharing your project, it looks pretty interesting, I will take a deeper look.
