### ISSUE TITLE
nested rules (AND / OR) support

### ISSUE THREAD

**Issue by rogaha** [afedulov/fraud-detection-demo#6]
Firstly, I would like to thank you for sharing this project with the community -- this is an awesome implementation of a `rules engine` with `Flink` for simple `aggregations`. 

@afedulov, I was wondering what would be your suggestion to add support for `nesting/complex` rules. Do you have an idea on how would be the best way to implement it? 

### Example: 
- `transactionAmount` is greater than 100 AND lower than 200`

**Comment by afedulov** [comment]
Hi @rogaha,
It depends on how arbitrarily complex you need to make your rules. In the example you gave it is pretty straightforward - you have all the data in the same process function and it boils down to correctly interpreting your DSL language. Some pointers would be Abstract Syntax Trees and [ANTLR](https://pragprog.com/titles/tpantlr2/the-definitive-antlr-4-reference/). 
If you need to combine rules that group according to different keys, things become more complex. Consider the following example:

```
{
  "ruleId": 1,
  "ruleState": "ACTIVE",
  "groupingKeyNames": ["payerId", "beneficiaryId"],
  "aggregateFieldName": "paymentAmount",
  "aggregatorFunctionType": "SUM",
  "limitOperatorType": "GREATER",
  "limit": 1000000,
  "windowMinutes": 10080
}
AND
{
  "ruleId": 1,
  "ruleState": "ACTIVE",
  "groupingKeyNames": ["payerId"],
  "aggregateFieldName": "TRANSACTION_COUNT",
  "aggregatorFunctionType": "SUM",
  "limitOperatorType": "GREATER",
  "limit": 100,
  "windowMinutes": 1440
}
```
Alert if more than X amount of money was transferred between from the same payer to the same beneficiary within a week, if the payer made more than 100 transactions a day.
In this case you'd need to calculate aggregations based on two different keys ["payerId", "beneficiaryId"] and ["payerId"]. In a static Flink program, you'd need to have two `keyBy()` calls for that. 

```
DataStream<Alert> alerts =
    transactions
        .process(new DynamicKeyFunction())
        .keyBy((keyed) -> keyed.getKey());
        .process(new DynamicAlertFunctionStageOne())
		.keyBy((keyed) -> keyed.getKey())
		.process(new DynamicAlertFunctionStageTwo());
```
You would ongoingly calculate the sum of the first aggregation and pass the result to the second stage, together with the updated key (["payerId"]) for the second grouping and the final evaluation. I think it is clear that here you hit the limit of how complex the rule can be - if you only defined two `keyBy` operators in your job graph, you can only support one chaining of complex rules. 
In order to be generic in evaluating arbitrarily complex rules you would need to have some sort of an interpreter that would not depend on the graph structure of your job. The simplest such "interpreter" could be a loop, where you evaluate things and "pass them" back as the "enriched" input and instructions what to do next. Flink has [Iterations](https://ci.apache.org/projects/flink/flink-docs-master/api/java/org/apache/flink/streaming/api/datastream/IterativeStream.html), but in vanilla Flink they do not support checkpointing, which is a major drawback. Using vanilla Flink you can still get the same result by looping results of the computation though an external component - writing results of every evaluation "state" to Kafka and reading them back as the input in the same job (you could use SideOutputs to distinguish between the final and intermediate results).

Another alternatives is to look into [StatefulFunctions](https://flink.apache.org/stateful-functions.html), which are built on top of the Flink runtime, but support arbitrary addressing while still maintaining fault tolerance guarantees. 

P.S.: I am happy to share my thoughts, but please next time ask such questions in the comments section of the blog post - the code base Issues section are not the right place for this.

**Comment by rogaha** [comment]
@afedulov thanks a lot for the thoughtful answer. I'll explore your suggestion of using `SideOutputs` with `Kafka` and I let you know how it goes. 

I thought it would be interesting to raise the `issue` here, so that we can contribute to your project. But, I'm happy to continue the conversation on the blog post.

Thanks again for your feedback. I appreciate it.

**Comment by afedulov** [comment]
>  I'll explore your suggestion of using SideOutputs with Kafka and I let you know how it goes. 
Great. I am closing this for now. Let me know when/if you have something  you would want to  contribute.
